# Generated by Django 5.1.4 on 2024-12-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologos', '0002_agendamento_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
